defaults:
  - tasks@: imagenav
  - experiments@: imagenav_rl
  - model: vc1_vitl
  - model/transform: jitter_and_shift
  - wandb_habitat@: habitat_vc
  - override hydra/output: path
  - override hydra/launcher: slurm_eval
  - _self_

RUN_TYPE: eval
NUM_ENVIRONMENTS: 14
